// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build and absent in a clean checkout.
import nextHandler from "./.open-next/worker.js";
import { createAuth } from "./src/auth/server";
import { purgeExpiredTombstones } from "./src/platform/purge";

export { TripRoom } from "./src/platform/trip-room";

const liveRoute = /^\/api\/trips\/([^/]+)\/live$/;

export default {
  async fetch(request, env, ctx): Promise<Response> {
    const url = new URL(request.url);
    const match = url.pathname.match(liveRoute);
    if (match && (request.headers.get("Upgrade") === "websocket" || request.method === "PATCH")) {
      const session = await createAuth(env).api.getSession({ headers: request.headers });
      if (!session) return new Response("Unauthorized", { status: 401 });
      const tripId = decodeURIComponent(match[1]);
      const membership = await env.DB.prepare(
        "select role from trip_members where trip_id = ?1 and user_id = ?2",
      )
        .bind(tripId, session.user.id)
        .first();
      if (!membership) return new Response("Forbidden", { status: 403 });
      const forwarded = new Request(request);
      forwarded.headers.set("X-Nightthread-User-Id", session.user.id);
      forwarded.headers.set("X-Nightthread-User-Name", session.user.name);
      return env.TRIP_ROOMS.getByName(tripId).fetch(forwarded);
    }
    return nextHandler.fetch(request, env, ctx);
  },
  async scheduled(_controller, env, ctx): Promise<void> {
    ctx.waitUntil(purgeExpiredTombstones(env));
  },
} satisfies ExportedHandler<CloudflareEnv>;
