/* eslint-disable @next/next/no-html-link-for-pages */
import { ArrowLeft, ImagePlus } from "lucide-react";
import { createTrip } from "@/app/trips/new/actions";
import { Brand } from "@/components/brand";

const field = "mt-2 h-12 w-full rounded-xl border border-[var(--line)] bg-[var(--night)] px-3 text-sm";
export default function NewTripPage() {
  return <main className="min-h-screen"><header className="flex h-16 items-center border-b border-[var(--line)] px-6 md:px-10"><Brand /><a href="/trips" className="muted ml-auto flex items-center gap-2 text-sm hover:text-white"><ArrowLeft size={15} />Back to trips</a></header><div className="mx-auto max-w-2xl px-6 py-12"><p className="eyebrow">A new thread</p><h1 className="display mt-2 text-6xl">Where are you going?</h1><p className="muted mt-4 max-w-lg leading-7">Start with the shape of the trip. Dates can move without disturbing your day-by-day plan.</p><form action={createTrip} className="mt-10 space-y-6"><label className="block text-sm font-medium">Trip name<input name="name" required placeholder="Tokyo after dark" className={field} /></label><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-medium">Start date <span className="muted font-normal">optional</span><input name="startDate" type="date" className={field} /></label><label className="block text-sm font-medium">End date <span className="muted font-normal">optional</span><input name="endDate" type="date" className={field} /></label></div><div className="grid gap-4 md:grid-cols-[1fr_140px]"><label className="block text-sm font-medium">Starting location<input name="startingLocation" placeholder="New York, NY" className={field} /></label><label className="block text-sm font-medium">Currency<select name="currency" defaultValue="USD" className={field}><option>USD</option><option>EUR</option><option>GBP</option><option>JPY</option></select></label></div><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-medium">First city<input name="firstCity" required placeholder="Tokyo" className={field} /></label><label className="block text-sm font-medium">City timezone<input name="timezone" defaultValue="Asia/Tokyo" className={field} /></label></div><button type="button" className="flex h-32 w-full items-center justify-center gap-3 rounded-2xl border border-dashed border-[var(--line)] text-sm text-[var(--muted)] hover:border-[var(--faint)] hover:text-white"><ImagePlus size={19} />Add a cover image <span className="text-xs text-[var(--faint)]">JPEG, PNG or WebP</span></button><button className="h-12 w-full rounded-xl bg-[var(--ink)] text-sm font-semibold text-[var(--night)]">Create trip</button></form></div></main>;
}
