/* eslint-disable @next/next/no-img-element -- provider images must remain hotlinked. */
import { MapPin, Plus } from "lucide-react";
import { requireTripMember } from "@/auth/access";
import { createManualIdea } from "@/app/trips/[tripId]/actions";
import { VoteButton } from "@/components/vote-button";
import { getDemoTripFixture } from "@/lib/demo-trips";
import { loadTripWorkspace } from "@/lib/trip-workspace";

const field = "mt-2 h-11 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-raised)] px-3 text-sm text-[var(--ink)]";

export default async function IdeasPage({ params }: { params: Promise<{ tripId: string }> }) {
  const { tripId } = await params;
  const fixture = getDemoTripFixture(tripId);
  const member = fixture ? null : await requireTripMember(tripId);
  const workspace = fixture ?? (member ? await loadTripWorkspace(tripId, member.user) : null);
  if (!workspace) return null;
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Shared possibility space</p><h1 className="display mt-2 text-5xl">Saved ideas</h1></div>{workspace.persistence === "d1" && <a href="#add-idea" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[var(--indigo)] px-4 text-sm font-semibold text-white hover:bg-[var(--indigo-hover)]"><Plus size={15} />Add an idea</a>}</div>
    {workspace.persistence === "d1" && <section id="add-idea" className="mt-8 scroll-mt-24 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><div><p className="eyebrow">Manual entry</p><h2 className="mt-2 text-lg font-semibold">Save a place or possibility</h2><p className="muted mt-1 text-sm">Manual entry always works, even when place search or imagery is unavailable.</p></div><form action={createManualIdea.bind(null, tripId)} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Name<input name="name" required placeholder="Széchenyi Thermal Bath" className={field} /></label><label className="text-sm font-medium">City<select name="cityId" className={field} defaultValue=""><option value="">Unassigned</option>{workspace.cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label><label className="text-sm font-medium">Address or area<input name="address" placeholder="Állatkerti krt. 9-11" className={field} /></label><label className="text-sm font-medium">Priority<select name="priority" defaultValue="would_like" className={field}><option value="must_do">Must do</option><option value="would_like">Would like</option><option value="if_time">If time</option></select></label><label className="text-sm font-medium">Latitude <span className="muted font-normal">optional</span><input name="lat" type="number" step="any" className={field} /></label><label className="text-sm font-medium">Longitude <span className="muted font-normal">optional</span><input name="lon" type="number" step="any" className={field} /></label><label className="text-sm font-medium md:col-span-2">Notes<textarea name="notes" rows={3} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--surface-raised)] p-3 text-sm text-[var(--ink)]" /></label><button className="h-11 rounded-xl bg-[var(--indigo)] px-5 text-sm font-semibold text-white md:col-span-2">Save idea</button></form></section>}
    {workspace.ideas.length > 0 ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{workspace.ideas.map((idea) => <article key={idea.id} className="surface overflow-hidden rounded-2xl">{idea.image ? <img src={idea.image} alt="" className="h-44 w-full object-cover" /> : <div className="grid h-44 place-items-center bg-[var(--indigo-soft)] text-[var(--indigo)]"><MapPin size={28} /><span className="sr-only">No image added</span></div>}<div className="p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold">{idea.name}</h2><p className="muted mt-1 line-clamp-2 text-xs">{idea.detail}</p></div><VoteButton initialCount={idea.votes} initialActive={idea.userVoted} tripId={workspace.persistence === "d1" ? tripId : undefined} ideaId={workspace.persistence === "d1" ? idea.id : undefined} /></div><div className="mt-5 flex items-center justify-between text-[10px] font-semibold uppercase tracking-wider"><span className="text-[var(--thread-hover)]">{idea.priority.replace("_", " ")}</span>{idea.scheduled && <span className="text-[var(--positive)]">Scheduled</span>}</div></div></article>)}</div> : <section className="mt-8 rounded-2xl border border-dashed border-[var(--line)] bg-[var(--surface)] py-16 text-center"><MapPin className="mx-auto text-[var(--faint)]" /><h2 className="mt-4 text-lg font-semibold">No saved ideas yet</h2><p className="muted mt-2 text-sm">Start with the places you already know you want to consider.</p></section>}
    <p className="muted mt-8 text-xs">Place search powered by Geoapify when configured. Manual entry never depends on a provider.</p></main>;
}
